-- 060_instagram_venue_credentials.sql
-- TAC-516: a venue's own Instagram access token, per venue, encrypted at rest.
--
-- WHY THIS EXISTS. Until now there is exactly one Instagram token in the whole
-- system: INSTAGRAM_ACCESS_TOKEN, a single environment variable holding a
-- token generated by hand for the `theanalog.company` test account. It has two
-- production readers (lib/messaging/instagram/send-target.ts and
-- refresh-profile.ts). Every venue would need someone to make a token by hand
-- and re-make it every 60 days, and a missed one silently stops that venue's
-- Instagram messaging.
--
-- THE TOKEN HALF SHIPS BEFORE THE BUTTON, deliberately (ruled 2026-09-24).
-- After this table and its refresh job exist, the EXISTING long-lived token
-- can be inserted as one row by hand and automated refresh keeps it alive from
-- then on — which retires the ~16 Nov 2026 manual deadline recorded on TAC-460
-- with no dependency on Meta, OAuth, App Review or the operator app, all of
-- which are gated on someone else. The OAuth connect flow then writes the same
-- row through a different door.
--
-- NOTHING CHANGES ON THE DAY THIS APPLIES. No venue has a row, so the token
-- resolver falls back to INSTAGRAM_ACCESS_TOKEN and every send and profile
-- refresh behaves exactly as it does today. A venue's behaviour changes only
-- once it has a row here.
--
-- WHY A DEDICATED TABLE rather than widening `pos_credentials` (migration 030):
--   - that table is keyed (venue_id, provider) around a POS integration, and
--     its `merchant_external_id` would have to stand in for the Instagram
--     account id, which is already a real routing column on `venues`;
--   - it has no slot for the account's username, which the operator app shows;
--   - it carries `refresh_token_enc`, and Instagram Login has no refresh-token
--     concept at all — a long-lived token refreshes ITSELF.
--   Widening a POS-specific table with non-POS columns for a provider whose
--   auth model does not match is the wrong direction. Same shape, same crypto
--   discipline, own table.
--
-- NO instagram_account_id COLUMN HERE, on purpose. That stays canonical on
-- `venues.instagram_account_id` (migration 048), which already carries global
-- uniqueness and is what all five of its readers already read: the webhook's
-- venue lookup, the send target, the profile refresh, the follow-up engine and
-- the operator's Instagram dispatch. A second copy here would be a second
-- thing to disagree, and the cross-venue conflict rule (below) depends on
-- there being exactly one place an account id lives.
--
-- THE CROSS-VENUE RULE (ruled 2026-09-23, question 1). Connecting an Instagram
-- account already linked to a DIFFERENT venue is refused, and the original
-- venue is left connected. Moving an account between venues is a deliberate,
-- separate action nobody can trigger by accident. That rule is enforced in the
-- callback route, and `venues.instagram_account_id`'s existing UNIQUE
-- constraint is its backstop for the concurrent case.
--
-- WHY BOTH connected_at AND last_refreshed_at. Meta refuses to refresh a token
-- less than 24 hours old (TAC-460 AC5), so the refresh job needs the token's
-- AGE, not just its expiry. `greatest(connected_at, coalesce(last_refreshed_at,
-- connected_at))` is that anchor. Neither column alone answers it.
--
-- PURELY ADDITIVE: one new table, no drops, no column changes, no tightened
-- constraints. Per CLAUDE.md's ordering rule the apply can land before or
-- after the deploy. Applied in Studio by Jaipal; nothing in this repo runs it.

begin;

-- Brief, and only against venues/operators for the foreign keys. Both are tiny
-- and neither is on the webhook's hot path, but the timeout costs nothing and
-- a busy moment should fail this cleanly rather than queue behind it (048).
set local lock_timeout = '5s';

create table instagram_credentials (
  id uuid primary key default gen_random_uuid(),

  -- UNIQUE, not just indexed: one connected Instagram account per venue. A
  -- venue reconnecting (to the same account or another it owns) UPSERTs this
  -- row rather than accumulating rows, so there is never a question of which
  -- credential is live. ON DELETE CASCADE because a credential for a deleted
  -- venue is pure secret material with nothing left to authorise.
  venue_id uuid not null unique references venues(id) on delete cascade,

  -- The connected account's handle, shown to the operator ("lemilscoffee").
  -- Nullable: Meta can answer /me without one, and a missing handle must cost
  -- the handle rather than the whole connection.
  instagram_username text,

  -- AES-256-GCM, "<ivB64>.<tagB64>.<ciphertextB64>", keyed by
  -- INSTAGRAM_TOKEN_ENC_KEY. NEVER the raw token: this column is the reason
  -- lib/messaging/instagram/token-crypto.ts exists. A plaintext token here
  -- would be readable by anything holding a database connection, including
  -- every script in this repo.
  access_token_enc text not null,

  -- When Meta says this token stops working. Long-lived tokens last ~60 days.
  -- NOT NULL: a credential whose expiry is unknown cannot be refreshed on time
  -- and would silently fall out of the refresh scan, which is the exact
  -- failure this table exists to prevent.
  token_expires_at timestamptz not null,

  connected_at timestamptz not null default now(),

  -- Who connected it. Nullable and ON DELETE SET NULL: an operator leaving
  -- must never cascade away a live venue credential, and the audit value of
  -- knowing who connected it does not outrank the venue's messaging working.
  connected_by_operator_id uuid references operators(id) on delete set null,

  last_refreshed_at timestamptz,

  -- The last refresh failure, so it is visible without reading Slack history.
  -- Carries Meta's error code and our own reason string, NEVER a token and
  -- never Meta's error message (which quotes the object it failed on).
  last_refresh_error text,
  last_refresh_error_at timestamptz,

  -- Set when Meta's deauthorize callback fires, or the venue disconnects.
  deauthorized_at timestamptz,

  -- False once deauthorized or hard-disconnected. Kept as its own flag rather
  -- than derived from deauthorized_at so a future "disabled for another
  -- reason" does not have to lie about having been deauthorized.
  is_active boolean not null default true,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- The refresh scan: "which live credentials are near expiry". Partial, so it
-- stays small and never carries deauthorized rows the scan must skip anyway.
create index idx_instagram_credentials_expiry
  on instagram_credentials (token_expires_at)
  where is_active;

create trigger trg_instagram_credentials_updated_at
  before update on instagram_credentials
  for each row execute function set_updated_at();

comment on table instagram_credentials is
  'TAC-516: one row per venue holding that venue''s own Instagram access token, encrypted with INSTAGRAM_TOKEN_ENC_KEY. A venue with no row falls back to the INSTAGRAM_ACCESS_TOKEN env var. The account id itself lives on venues.instagram_account_id, not here.';

comment on column instagram_credentials.access_token_enc is
  'AES-256-GCM ciphertext, never a raw token. Encrypt and decrypt only through lib/messaging/instagram/token-crypto.ts.';

comment on column instagram_credentials.connected_at is
  'With last_refreshed_at, gives the token''s AGE. Meta refuses to refresh a token under 24 hours old, so the refresh job needs age as well as expiry.';

commit;

-- rollback:
--   begin;
--   drop table if exists instagram_credentials;
--   commit;
--
-- Safe as long as the deployed code still has its env-var fallback, which is
-- every version shipped by TAC-516: a venue with no credential row resolves
-- INSTAGRAM_ACCESS_TOKEN and behaves exactly as it did before this migration.
-- Dropping the table therefore returns the fleet to the shared token rather
-- than breaking a send. The refresh cron degrades to scanning nothing.
--
-- It DOES destroy any per-venue token stored so far. Those are recoverable
-- only by re-running the connect flow for each affected venue (or re-inserting
-- by hand), so check for rows before dropping:
--   select venue_id, instagram_username, token_expires_at from instagram_credentials;
