// TAC-516: put an EXISTING Instagram token into instagram_credentials, by
// hand, for one venue. Run by a person who means it.
//
// WHY THIS EXISTS. The token half of TAC-516 ships before the Connect button,
// and this is what makes that worth anything: Le Mil's is served today by a
// long-lived token generated by hand for the `theanalog.company` account
// (INSTAGRAM_ACCESS_TOKEN, expiring ~16 Nov 2026). Once that token is a row in
// instagram_credentials, the daily refresh keeps it alive from then on, with
// no dependency on Meta, OAuth, App Review or the operator app. That retires
// the November deadline without waiting for anyone.
//
// NOTHING IS PASTED. Both secrets come from .env.local, which already holds
// INSTAGRAM_ACCESS_TOKEN; the only thing to add is INSTAGRAM_TOKEN_ENC_KEY,
// the same value that goes on Vercel. So the run is one command and no secret
// reaches your shell history, your clipboard or this file.
//
// IT DOES NOT TRUST THE TOKEN'S OWNER. The account id is read from META
// (GET /me?fields=user_id,username), never assumed from the venue row, and
// then checked against the cross-venue rule in both directions. A token for
// the wrong account is the one mistake this script exists to catch, because
// the resulting row looks entirely correct and every send goes out from
// somebody else's Instagram.
//
// IT REFRESHES BEFORE STORING, and that is the point rather than a nicety.
// GET /me answers with no expiry, so a stored expiry would have to be guessed
// — and migration 060 makes token_expires_at NOT NULL precisely because a
// credential whose expiry is unknown falls out of the refresh scan and dies
// silently, which is the failure this whole ticket is about. Refreshing
// returns a new token AND a real expires_in, so the row is exact. Meta refuses
// to refresh a token under 24 hours old; the one in .env.local is months old,
// so that is not a case this hits. --expires-at is the escape hatch if Meta
// refuses for some other reason, and it is never a default.
//
// IT VERIFIES THE ROUND TRIP. After writing, it resolves the venue's token
// back through the real production path and asserts the source is `venue`
// rather than `env`. That is what proves the encryption key on this machine
// matches the one the row was written with — a mismatch stores cleanly and
// fails at the first send, hours later, as `token_unreadable`.
//
// Usage:
//   npm run insert-instagram-credential -- --venue le-mils-coffee --dry-run
//   npm run insert-instagram-credential -- --venue le-mils-coffee --confirm
//
// It prints the venue, the handle, the account id and the new expiry. It NEVER
// prints a token, refreshed or otherwise.

import { createAdminClient } from '@/lib/db/admin'
import {
  resolveInstagramAccessToken,
  upsertInstagramCredential,
} from '@/lib/messaging/instagram/credentials-store'
import {
  fetchConnectedAccount,
  refreshInstagramLongLivedToken,
} from '@/lib/messaging/instagram/oauth-exchange'
import {
  INSTAGRAM_TOKEN_ENC_KEY_VAR,
  checkInstagramTokenEncKey,
} from '@/lib/messaging/instagram/token-crypto'

import { isTokenRejected } from '@/lib/messaging/instagram/graph'

import {
  decideAccountClaim,
  describeGraphFailure,
  parseInsertArgs,
} from './lib/insert-instagram-credential'

function die(message: string): never {
  console.error(`\n✗ ${message}\n`)
  process.exit(1)
}

async function main(): Promise<void> {
  const parsed = parseInsertArgs(process.argv.slice(2))
  if (!parsed.ok) die(`${parsed.error}\n\n  npm run insert-instagram-credential -- --venue <slug> --confirm`)
  const args = parsed.args

  // 1. The encryption key, before anything else: without it the write cannot
  //    happen and every later step would be wasted work.
  const keyCheck = checkInstagramTokenEncKey(process.env)
  if (!keyCheck.ok) {
    die(
      `${keyCheck.detail}\n\n` +
        `  Generate one:  openssl rand -base64 32\n` +
        `  Then put the SAME value in .env.local and on Vercel (Production and Preview)\n` +
        `  as ${INSTAGRAM_TOKEN_ENC_KEY_VAR}. A different value in the two places stores\n` +
        `  cleanly here and fails at the first send.`,
    )
  }

  const envToken = (process.env.INSTAGRAM_ACCESS_TOKEN ?? '').trim()
  if (envToken === '') {
    die('INSTAGRAM_ACCESS_TOKEN is not set in .env.local. That is the existing token this stores.')
  }

  const supabase = createAdminClient()

  // 2. The venue.
  const venue = await supabase
    .from('venues')
    .select('id, name, instagram_account_id')
    .eq('slug', args.venueSlug)
    .maybeSingle()
  if (venue.error) die(`could not read the venue: ${venue.error.message}`)
  if (!venue.data) die(`no venue with slug "${args.venueSlug}"`)
  const venueId = venue.data.id
  const targetAccountId = venue.data.instagram_account_id

  console.log(`\nVenue:   ${venue.data.name} (${args.venueSlug})`)
  console.log(`Pointer: venues.instagram_account_id = ${targetAccountId ?? '(unset)'}`)

  // 3. Ask META who the token belongs to. Never assume it is the venue's.
  const account = await fetchConnectedAccount(envToken, fetch)
  if (!account.ok) {
    die(
      `Meta would not identify the token: ${describeGraphFailure(account.failure)}.\n` +
        (isTokenRejected(account.failure)
          ? `  That is Meta rejecting the token itself — expired, revoked or invalid. It\n` +
            `  cannot be refreshed past expiry, so the venue has to reconnect instead.`
          : `  Nothing was written. Re-run once Meta answers.`),
    )
  }
  const tokenAccountId = account.value.userId
  console.log(`Token:   belongs to account ${tokenAccountId} (@${account.value.username ?? 'unknown'})`)

  // 4. Who else holds that account. One row at most: the column is globally
  //    unique (migration 048).
  const holder = await supabase
    .from('venues')
    .select('id')
    .eq('instagram_account_id', tokenAccountId)
    .maybeSingle()
  if (holder.error) die(`could not check which venue holds that account: ${holder.error.message}`)

  const decision = decideAccountClaim({
    targetVenueId: venueId,
    targetAccountId,
    holderVenueId: holder.data?.id ?? null,
    tokenAccountId,
  })
  if (decision.action === 'refuse') die(decision.reason)
  console.log(`Account: ${decision.action === 'claim' ? 'will be claimed by this venue' : 'already pointed here'}`)

  // Both exits sit HERE, above the refresh, and the ordering is the point: a
  // refresh ISSUES A NEW TOKEN at Meta, so it is not a read. A --dry-run that
  // reached it would change state at Meta while printing that it had changed
  // nothing, which is worse than having no dry run at all.
  if (args.dryRun || !args.confirm) {
    const why = args.dryRun ? '--dry-run' : 'no --confirm'
    console.log(
      `\n· ${why}: nothing was written, and the token was NOT refreshed.\n` +
        `  With --confirm this would refresh the token (issuing a new one, with a real\n` +
        `  expiry), store it against this venue, and verify the venue resolves its own\n` +
        `  credential afterwards.\n`,
    )
    return
  }

  // 5. Refresh, so the stored expiry is Meta's rather than a guess.
  let accessToken = envToken
  let expiresAt: Date
  const refreshed = await refreshInstagramLongLivedToken(envToken, fetch, new Date())
  if (refreshed.ok) {
    accessToken = refreshed.value.token
    expiresAt = refreshed.value.expiresAt
    console.log(`Refresh: new token, expires ${expiresAt.toISOString()}`)
  } else if (args.expiresAtOverride) {
    expiresAt = args.expiresAtOverride
    console.log(
      `Refresh: REFUSED (${describeGraphFailure(refreshed.failure)}); storing the existing token\n` +
        `         --expires-at you supplied, ${expiresAt.toISOString()}`,
    )
  } else {
    die(
      `Meta refused to refresh the token: ${describeGraphFailure(refreshed.failure)}.\n` +
        `  Without a refresh there is no expiry to store, and a guessed one drops the row\n` +
        `  out of the refresh scan silently — which is the failure this table exists to stop.\n` +
        `  Re-run with --expires-at <ISO> only if you know the real expiry.`,
    )
  }

  // 6. Write, through the production path rather than a parallel one.
  const now = new Date()
  const stored = await upsertInstagramCredential(supabase, {
    venueId,
    accessToken,
    tokenExpiresAt: expiresAt,
    instagramUsername: account.value.username,
    connectedByOperatorId: args.operatorId,
    now,
  })
  if (!stored.ok) die(`could not store the credential: ${stored.error}`)
  console.log('Stored:  instagram_credentials row written')

  // 7. Point the venue, only when it has no pointer. Never move one.
  if (decision.action === 'claim') {
    const pointed = await supabase
      .from('venues')
      .update({ instagram_account_id: tokenAccountId })
      .eq('id', venueId)
    if (pointed.error) {
      die(
        `the credential was stored but the venue pointer was NOT set: ${pointed.error.message}\n` +
          `  The venue cannot send until venues.instagram_account_id = ${tokenAccountId}.`,
      )
    }
    console.log(`Pointed: venues.instagram_account_id = ${tokenAccountId}`)
  }

  // 8. Prove the round trip: encrypt -> store -> decrypt -> resolve. A key
  //    mismatch is invisible until this runs.
  const check = await resolveInstagramAccessToken(supabase, venueId)
  if (!check.ok) die(`stored, but reading it back failed: ${check.error}`)
  if (check.resolved === null || check.resolved.source !== 'venue') {
    die(
      `stored, but this venue still resolves to the ${check.resolved?.source ?? 'missing'} token.\n` +
        `  The row is not being used. Check is_active and deauthorized_at on the row.`,
    )
  }
  console.log(`Verified: the venue now resolves its OWN credential (expires ${check.resolved.expiresAt?.toISOString()})`)

  console.log(
    `\n✓ Done. ${venue.data.name} sends with its own token from now on, and the daily\n` +
      `  refresh keeps it alive. INSTAGRAM_ACCESS_TOKEN is now only the fallback for\n` +
      `  venues with no row, and can be removed once every venue has one.\n`,
  )
}

main().catch((err) => {
  console.error('\n✗ unexpected failure:', err instanceof Error ? err.message : err, '\n')
  process.exit(1)
})
