'use client'

import { formatInTimeZone } from 'date-fns-tz'
import { Card, Eyebrow, HairlineRow, SectionHeader } from '@/lib/ui'

// Side panel for when the operator clicks an inbound (guest) message.
// Inbound rows have no Langfuse trace — they weren't generated by the agent —
// so we render metadata + the body, plus a link to the *outbound* reply that
// was triggered by this inbound (if there is one), so the operator can pivot
// from "what did the guest say" to "what did the agent reply with."

export interface InboundDetailProps {
  message: {
    id: string
    body: string
    createdAt: Date
    providerMessageId: string | null
  }
  guestName: string
  guestPhone: string
  venueTimezone: string
  triggeredOutboundId: string | null
  onSelectOutbound: (id: string) => void
}

export function InboundDetail({
  message,
  guestName,
  guestPhone,
  venueTimezone,
  triggeredOutboundId,
  onSelectOutbound,
}: InboundDetailProps) {
  return (
    <aside className="w-full h-full min-h-0 flex flex-col gap-6 p-6 bg-paper/50 border-l border-stone-light/60 overflow-y-auto">
      <div className="flex flex-col gap-2">
        <Eyebrow>Inbound message</Eyebrow>
        <SectionHeader
          title={guestName}
          subtitle={formatInTimeZone(message.createdAt, venueTimezone, 'h:mm a · EEE MMM d')}
        />
      </div>

      <Card>
        <div className="flex flex-col">
          <HairlineRow>
            <Row label="Phone">
              <span className="font-fraunces-text">{guestPhone}</span>
            </Row>
          </HairlineRow>
          <HairlineRow>
            <Row label="Message ID">
              <span className="text-xs font-fraunces-text break-all">{message.id}</span>
            </Row>
          </HairlineRow>
          <HairlineRow last={!message.providerMessageId}>
            <Row label="Provider ID">
              <span className="text-xs font-fraunces-text break-all">
                {message.providerMessageId ?? '—'}
              </span>
            </Row>
          </HairlineRow>
          {message.providerMessageId ? (
            <HairlineRow last>
              <Row label="Received at">
                <span>{formatInTimeZone(message.createdAt, venueTimezone, 'yyyy-MM-dd HH:mm:ss zzz')}</span>
              </Row>
            </HairlineRow>
          ) : null}
        </div>
      </Card>

      <Card>
        <div className="flex flex-col gap-2">
          <Eyebrow>Body</Eyebrow>
          <pre className="text-sm whitespace-pre-wrap break-words text-ink">{message.body}</pre>
        </div>
      </Card>

      {triggeredOutboundId ? (
        <button
          type="button"
          onClick={() => onSelectOutbound(triggeredOutboundId)}
          className="self-start text-sm text-clay hover:underline cursor-pointer"
        >
          View triggered agent reply →
        </button>
      ) : (
        <div className="text-xs text-ink-soft">
          No outbound reply linked to this inbound (yet, or the agent skipped it).
        </div>
      )}
    </aside>
  )
}

function Row({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex items-baseline justify-between gap-4">
      <span className="text-sm text-ink-soft">{label}</span>
      <span className="text-sm text-ink text-right max-w-[60%]">{children}</span>
    </div>
  )
}
